version: "3.9"

services:
  frontend:
    container_name: damola_portfolio_frontend
    image: ${{ secrets.DOCKER_USERNAME }}/damola_portfolio_frontend:latest
    ports:
      - "3003:3000"

networks:
  web:
    external: true
