version: "3.9"

services:
  frontend:
    container_name: dk-portforlio-frontend
    build:
      context: .
      target: dev
      dockerfile: dev.dockerfile
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3003:3000"
